import type { ModuleData } from "./types.js";

export default {
    modules: {
        modules: { name: "Manage Modules", commands: ["modules"] },
        admin: { name: "Admin Controls", commands: ["admin"] },
        core: {
            name: "Core",
            icon: "label_important_outline",
            description: "Core commands for managing and configuring the bot.",
            commands: ["settings"],
        },
        welcome: {
            name: "Welcome",
            icon: "waving_hand",
            description: "Welcome incoming members to the server.",
            commands: [],
        },
        "supporter-announcements": {
            name: "Supporter Announcements",
            icon: "campaign",
            description: "Announce new boosters and other server supporters by role.",
            commands: [],
        },
        xp: {
            name: "XP",
            icon: "sort",
            description: "Server experience system to reward active members.",
            commands: ["top", "rank", "mee6-import", "reset-xp"],
        },
        "reaction-roles": {
            name: "Reaction Roles",
            icon: "add_reaction",
            description: "Allow users to self-assign roles, including verification roles.",
            self_permissions: ["ManageRoles", "ManageMessages"],
            commands: [],
        },
        moderation: {
            name: "Moderation",
            icon: "shield",
            description: "Moderation commands for managing users and content.",
            commands: [
                "ban",
                "kick",
                "mute",
                "timeout",
                "warn",
                "unban",
                "unmute",
                "massban",
                "history",
                "delete-warn",
                "clear-warns",
                "slowmode",
                "purge",
                "notes",
            ],
        },
        starboard: {
            name: "Starboard",
            icon: "star",
            description: "Feature messages that receive a specified reaction.",
            commands: [],
        },
        automod: {
            name: "Automod",
            icon: "document_scanner",
            description: "Automatically scan messages and edits for problematic content.",
            self_permissions: ["ManageMessages", "ManageRoles", "ModerateMembers", "KickMembers", "BanMembers"],
            commands: [],
        },
        "sticky-roles": {
            name: "Sticky Roles",
            icon: "replay",
            description: "Automatically re-add roles to members when they rejoin the server.",
            self_permissions: "ManageRoles",
            commands: [],
            disable: true,
        },
        "custom-roles": {
            name: "Custom Roles",
            icon: "dashboard_customize",
            description: "Give boosters and other server supporters the ability to create custom roles.",
            self_permissions: "ManageRoles",
            commands: ["role"],
            disable: true,
        },
        "stats-channels": {
            name: "Stats Channels",
            icon: "insights",
            self_permissions: "ManageChannels",
            description: "Keep track of server stats with automatically updating channels.",
            commands: [],
        },
        autoresponder: {
            name: "Autoresponder",
            icon: "bolt",
            description: "Automatically respond to certain messages.",
            commands: [],
        },
    },
    commands: {
        modules: { name: "Manage Modules", permissions: "admin", ghost: true },
        admin: { name: "Admin Controls", permissions: "admin", ghost: true },
        settings: {
            name: "Settings",
            icon: "settings",
            permissions: "ManageGuild",
            self_permissions: "ManageWebhooks",
            description: "Manage bot settings.",
        },
        top: {
            name: "Top",
            icon: "leaderboard",
            description: "Get top users by XP.",
        },
        rank: {
            name: "Rank",
            icon: "military_tech",
            description: "Get a user's XP and rank.",
        },
        "mee6-import": {
            name: "MEE6 XP Import",
            icon: "import_export",
            permissions: "ManageGuild",
            description: "Import XP from MEE6",
        },
        "reset-xp": {
            name: "Reset XP",
            icon: "restart_alt",
            permissions: "ManageGuild",
            description: "Reset a user's XP irreversibly.",
        },
        ban: {
            name: "Ban",
            icon: "gavel",
            permissions: "BanMembers",
            self_permissions: "BanMembers",
            description: "Ban a user (even if they are not in the server).",
        },
        kick: {
            name: "Kick",
            icon: "person_remove",
            permissions: "KickMembers",
            self_permissions: "KickMembers",
            description: "Kick a member from the server.",
        },
        mute: {
            name: "Mute",
            icon: "volume_off",
            permissions: "ModerateMembers",
            self_permissions: "ManageRoles",
            description:
                "Mute a user by assigning them a mute role. This only works on non-members if the Sticky Roles module is enabled.",
        },
        timeout: {
            name: "Timeout",
            icon: "timer",
            permissions: "ModerateMembers",
            self_permissions: "ModerateMembers",
            description: "Timeout a member or remove their timeout.",
        },
        warn: {
            name: "Warn",
            icon: "warning",
            permissions: "ModerateMembers",
            description: "DM a warning to a user and log it to their user history.",
        },
        unban: {
            name: "Unban",
            icon: "manage_accounts",
            permissions: "BanMembers",
            self_permissions: "BanMembers",
            description: "Unban a user, allowing them to rejoin the server.",
        },
        unmute: {
            name: "Unmute",
            icon: "volume_up",
            permissions: "ModerateMembers",
            self_permissions: "ManageRoles",
            description:
                "Unmute a user by removing the mute role. This only works on non-members if the Sticky Roles module is enabled.",
        },
        massban: {
            name: "Massban",
            icon: "group_remove",
            permissions: "ManageGuild",
            self_permissions: "BanMembers",
            description: "Ban many users at once.",
        },
        history: {
            name: "History",
            icon: "history",
            permissions: "ModerateMembers",
            description: "View a user's history.",
        },
        "delete-warn": {
            name: "Delete History Entry",
            icon: "delete",
            permissions: "ManageGuild",
            description: "Remove a single history entry.",
        },
        "clear-warns": {
            name: "Clear History",
            icon: "manage_history",
            permissions: "ManageGuild",
            description: "Clear a user's history.",
        },
        slowmode: {
            name: "Slowmode",
            icon: "speed",
            bypass: true,
            permissions: "ManageChannels",
            self_permissions: "ManageChannels",
            description: "Set a channel's slowmode.",
        },
        purge: {
            name: "Purge",
            icon: "delete_sweep",
            permissions: "ManageGuild",
            self_permissions: "ManageMessages",
            description: "Purge many messages at once.",
        },
        notes: {
            name: "Notes",
            icon: "notes",
            permissions: "ModerateMembers",
            description: "Record mod notes for a user.",
        },
        role: {
            name: "Custom Role",
            icon: "format_color_fill",
            self_permissions: "ManageRoles",
            description: "Manage the user's custom role.",
        },
    },
} as ModuleData;
