import type { ModuleData } from "./types.js";

export default {
    modules: {
        modules: { name: "Manage Modules", commands: ["modules"] },
        admin: { name: "Admin Controls", commands: ["admin"] },
        core: {
            name: "Core",
            icon: "label_important_outline",
            description: "Core commands for managing and configuring the bot.",
            commands: ["settings"],
        },
        welcome: {
            name: "Welcome",
            icon: "waving_hand",
            description: "Welcome incoming members to the server.",
            commands: [],
        },
        "supporter-announcements": {
            name: "Supporter Announcements",
            icon: "campaign",
            description: "Announce new boosters and other server supporters by role.",
            commands: [],
        },
        xp: {
            name: "XP",
            icon: "sort",
            description: "Server experience system to reward active members.",
            commands: ["top", "rank", "mee6-import", "reset-xp"],
        },
        "reaction-roles": {
            name: "Reaction Roles",
            icon: "add_reaction",
            description: "Allow users to self-assign roles, including verification roles.",
            self_permissions: ["ManageRoles", "ManageMessages"],
            commands: [],
        },
        moderation: {
            name: "Moderation",
            icon: "shield",
            description: "Moderation commands for managing users and content.",
            commands: [
                "ban",
                "kick",
                "mute",
                "timeout",
                "warn",
                "unban",
                "unmute",
                "massban",
                "history",
                "delete-warn",
                "clear-warns",
                "slowmode",
                "purge",
                "notes",
            ],
        },
        starboard: {
            name: "Starboard",
            icon: "star",
            description: "Feature messages that receive a specified reaction.",
            commands: [],
        },
        automod: {
            name: "Automod",
            icon: "document_scanner",
            description: "Automatically scan messages and edits for problematic content.",
            self_permissions: ["ManageMessages", "ManageRoles", "ModerateMembers", "KickMembers", "BanMembers"],
            commands: [],
        },
        "sticky-roles": {
            name: "Sticky Roles",
            icon: "replay",
            description: "Automatically re-add roles to members when they rejoin the server.",
            self_permissions: "ManageRoles",
            commands: [],
            disable: true,
        },
        "custom-roles": {
            name: "Custom Roles",
            icon: "dashboard_customize",
            description: "Give boosters and other server supporters the ability to create custom roles.",
            self_permissions: "ManageRoles",
            commands: ["role"],
            disable: true,
        },
        "stats-channels": {
            name: "Stats Channels",
            icon: "insights",
            self_permissions: "ManageChannels",
            description: "Keep track of server stats with automatically updating channels.",
            commands: [],
        },
        autoresponder: {
            name: "Autoresponder",
            icon: "bolt",
            description: "Automatically respond to certain messages.",
            commands: [],
        },
        modmail: {
            name: "Modmail",
            icon: "mail",
            self_permissions: ["CreatePublicThreads", "ManageThreads", "ManageChannels"],
            description: "Allow users to contact staff through direct-messaging the bot.",
            commands: ["modmail"],
            disable: true,
        },
        tickets: {
            name: "Tickets",
            icon: "confirmation_number",
            self_permissions: "ManageChannels",
            description: "Allow users to contact staff by creating new private channels at the press of a button.",
            commands: ["ticket"],
        },
        nukeguard: {
            name: "Nukeguard",
            icon: "security",
            self_permissions: "BanMembers",
            description: "Anti-nuke features to guard against rogue or compromised mods/admins.",
            commands: [],
        },
        suggestions: {
            name: "Suggestions",
            icon: "feedback",
            description: "Allow members to give feedback to the server.",
            commands: ["suggest", "suggestion"],
        },
        "co-op": {
            name: "Co-op (Genshin Impact)",
            icon: "handshake",
            description: "Co-op group finding system for Genshin Impact.",
            commands: ["co-op"],
        },
        feeds: {
            name: "Feeds",
            icon: "rss_feed",
            description: "Subscribe to live updates from various other websites.",
            commands: ["feed"],
        },
        count: {
            name: "Counting Channels",
            icon: "123",
            self_permissions: "ManageMessages",
            description: "Counting Channels",
            commands: ["scoreboard"],
        },
        giveaways: {
            name: "Giveaways",
            icon: "celebration",
            description: "Set up giveaways for server members.",
            commands: ["reroll"],
        },
        reminders: {
            name: "Reminders",
            icon: "event",
            description: "Set reminders to occur in your DMs.",
            commands: ["reminder"],
        },
        reports: {
            name: "Reports",
            icon: "report_problem",
            description: "Allow members to report users and messages to moderators.",
            commands: ["Report User", "Flag Message", "report", "flag"],
            disable: true,
        },
        polls: {
            name: "Polls",
            icon: "poll",
            description: "Yes/No and multiple-choice polls.",
            commands: ["poll", "set-qotd-ping"],
        },
        highlights: {
            name: "Highlights",
            icon: "notifications",
            description: "Receive DM notifications for messages with certain terms.",
            commands: ["highlight"],
        },
        utility: {
            name: "Utility",
            icon: "handyman",
            description: "Utility commands for server management and other purposes.",
            commands: [
                "emoji-roles",
                "help",
                "info",
                "avatar",
                "roles",
                "format",
                "say",
                "code",
                "qr",
                "tex",
                "convert",
                "snowflake",
            ],
        },
        "sticky-messages": {
            name: "Sticky Messages",
            icon: "sticky_note_2",
            description: "Set messages to stick to the bottom of a channel.",
            commands: ["stick", "unstick", "sticklist"],
        },
        fun: {
            name: "Fun",
            icon: "attractions",
            description: "Fun commands. Mostly pointless/unimportant.",
            commands: ["random"],
        },
    },
    commands: {
        modules: { name: "Manage Modules", permissions: "admin", ghost: true },
        admin: { name: "Admin Controls", permissions: "admin", ghost: true },
        settings: {
            name: "Settings",
            icon: "settings",
            permissions: "ManageGuild",
            self_permissions: "ManageWebhooks",
            description: "Manage bot settings.",
        },
        top: {
            name: "Top",
            icon: "leaderboard",
            description: "Get top users by XP.",
            ghost: true,
        },
        rank: {
            name: "Rank",
            icon: "military_tech",
            description: "Get a user's XP and rank.",
            ghost: true,
        },
        "mee6-import": {
            name: "MEE6 XP Import",
            icon: "import_export",
            permissions: "ManageGuild",
            description: "Import XP from MEE6",
        },
        "reset-xp": {
            name: "Reset XP",
            icon: "restart_alt",
            permissions: "ManageGuild",
            description: "Reset a user's XP irreversibly.",
        },
        ban: {
            name: "Ban",
            icon: "gavel",
            permissions: "BanMembers",
            self_permissions: "BanMembers",
            description: "Ban a user (even if they are not in the server).",
        },
        kick: {
            name: "Kick",
            icon: "person_remove",
            permissions: "KickMembers",
            self_permissions: "KickMembers",
            description: "Kick a member from the server.",
        },
        mute: {
            name: "Mute",
            icon: "volume_off",
            permissions: "ModerateMembers",
            self_permissions: "ManageRoles",
            description:
                "Mute a user by assigning them a mute role. This only works on non-members if the Sticky Roles module is enabled.",
        },
        timeout: {
            name: "Timeout",
            icon: "timer",
            permissions: "ModerateMembers",
            self_permissions: "ModerateMembers",
            description: "Timeout a member or remove their timeout.",
        },
        warn: {
            name: "Warn",
            icon: "warning",
            permissions: "ModerateMembers",
            description: "DM a warning to a user and log it to their user history.",
        },
        unban: {
            name: "Unban",
            icon: "manage_accounts",
            permissions: "BanMembers",
            self_permissions: "BanMembers",
            description: "Unban a user, allowing them to rejoin the server.",
        },
        unmute: {
            name: "Unmute",
            icon: "volume_up",
            permissions: "ModerateMembers",
            self_permissions: "ManageRoles",
            description:
                "Unmute a user by removing the mute role. This only works on non-members if the Sticky Roles module is enabled.",
        },
        massban: {
            name: "Massban",
            icon: "group_remove",
            permissions: "ManageGuild",
            self_permissions: "BanMembers",
            description: "Ban many users at once.",
        },
        history: {
            name: "History",
            icon: "history",
            permissions: "ModerateMembers",
            description: "View a user's history.",
            ghost: true,
        },
        "delete-warn": {
            name: "Delete History Entry",
            icon: "delete",
            permissions: "ManageGuild",
            description: "Remove a single history entry.",
        },
        "clear-warns": {
            name: "Clear History",
            icon: "manage_history",
            permissions: "ManageGuild",
            description: "Clear a user's history.",
        },
        slowmode: {
            name: "Slowmode",
            icon: "speed",
            bypass: true,
            permissions: "ManageChannels",
            self_permissions: "ManageChannels",
            description: "Set a channel's slowmode.",
        },
        purge: {
            name: "Purge",
            icon: "delete_sweep",
            permissions: "ManageGuild",
            self_permissions: "ManageMessages",
            description: "Purge many messages at once.",
        },
        notes: {
            name: "Notes",
            icon: "notes",
            permissions: "ModerateMembers",
            description: "Record mod notes for a user.",
        },
        role: {
            name: "Custom Role",
            icon: "format_color_fill",
            self_permissions: "ManageRoles",
            description: "Manage the user's custom role.",
            ghost: true,
        },
        modmail: {
            name: "Modmail",
            icon: "mail",
            description: "Reply to or close modmail threads.",
        },
        ticket: {
            name: "Ticket",
            icon: "confirmation_number",
            description: "Manage tickets.",
        },
        suggest: {
            name: "Suggest",
            icon: "feedback",
            description: "Make a suggestion.",
            ghost: true,
        },
        suggestion: {
            name: "Manage Suggestions",
            icon: "forum",
            permissions: "ManageGuild",
            description: "Answer suggestions and view anonymous suggestion authors.",
        },
        "co-op": {
            name: "Co-op",
            icon: "group",
            description: "Find a co-op group.",
            ghost: true,
        },
        feed: {
            name: "Feed",
            icon: "rss_feed",
            permissions: "ManageGuild",
            description: "Set up or manage feeds.",
        },
        scoreboard: {
            name: "Scoreboard",
            icon: "leaderboard",
            description: "View the counting leaderboard.",
            ghost: true,
        },
        reroll: {
            name: "Reroll",
            icon: "replay",
            permissions: "ManageGuild",
            description: "Reroll a giveaway",
        },
        reminder: {
            name: "Reminders",
            icon: "event",
            description: "Set, list, or manage your reminders.",
            ghost: true,
        },
        "Report User": {
            name: "Report User",
            icon: "report",
            description: "Report a user (user context menu command).",
            ghost: true,
        },
        "Flag Message": {
            name: "Flag Message",
            icon: "flag",
            description: "Flag a message (message context menu command).",
            ghost: true,
        },
        report: {
            name: "Report User",
            icon: "report",
            description: "Report a user (slash command).",
            ghost: true,
        },
        flag: {
            name: "Flag Message",
            icon: "flag",
            description: "Flag a message (slash command).",
            ghost: true,
        },
        poll: {
            name: "Poll",
            icon: "poll",
            permissions: "ManageGuild",
            description: "Create a poll.",
        },
        "set-qotd-ping": {
            name: "Set QOTD Ping",
            icon: "alternate_email",
            permissions: "ManageGuild",
            description: "Set the role that is pinged when auto-posting QOTDs.",
        },
        highlight: {
            name: "Highlight",
            icon: "notifications",
            description: "Manage your highlights.",
            ghost: true,
        },
        "emoji-roles": {
            name: "Emoji Roles",
            icon: "filter_list",
            permissions: "ManageEmojisAndStickers",
            self_permissions: "ManageEmojisAndStickers",
            description: "Control which roles can use a server emoji.",
        },
        help: {
            name: "Help",
            icon: "help",
            description: "Get help for the bot.",
            ghost: true,
        },
        info: {
            name: "Info",
            icon: "info",
            description: "Get info for a user, role, channel, server, or invite.",
            ghost: true,
        },
        avatar: {
            name: "Avatar",
            icon: "account_box",
            description: "View a user's avatar.",
            ghost: true,
        },
        roles: {
            name: "Roles",
            icon: "theater_comedy",
            permissions: "ManageRoles",
            self_permissions: "ManageRoles",
            description: "Alter a user's roles.",
        },
        format: {
            name: "Format",
            icon: "text_format",
            description: "Convert a Discord message element into its source text.",
            ghost: true,
        },
        say: {
            name: "Say",
            icon: "chat",
            description: "Say a message.",
            permissions: "ManageGuild",
        },
        code: {
            name: "Code",
            icon: "redeem",
            description: "Display a Genshin Impact gift code.",
            ghost: true,
        },
        qr: {
            name: "QR",
            icon: "qr_code_scanner",
            description: "Convert any text into a QR code.",
            ghost: true,
        },
        tex: {
            name: "Render LaTeX",
            icon: "image",
            description: "Render LaTeX to a PNG file.",
            ghost: true,
        },
        convert: {
            name: "Convert Units",
            icon: "currency_exchange",
            description: "Convert between common units or between currencies.",
            ghost: true,
        },
        snowflake: {
            name: "Snowflake",
            icon: "ac_unit",
            description: "Deconstruct a Discord snowflake (ID).",
            ghost: true,
        },
        stick: {
            name: "Stick",
            icon: "label",
            permissions: "ManageChannels",
            description: "Set the channel's sticky message.",
        },
        unstick: {
            name: "Unstick",
            icon: "label_off",
            permissions: "ManageChannels",
            description: "Remove the channel's sticky message.",
        },
        sticklist: {
            name: "List Sticky Message",
            icon: "list",
            permissions: "ManageChannels",
            description: "List the server's sticky messages.",
        },
        random: {
            name: "Random",
            icon: "shuffle",
            description: "Random-related functions.",
            ghost: true,
        },
    },
} as ModuleData;
